### PR TITLE
 adding get_name() functionality 

### PR DESCRIPTION
**Pull request by TeaWithLucas**
means filename is character name if given

### CODE REVIEW

**Comment by TeaWithLucas** [comment]
Addition of Readme

**Comment by CaelumF** [comment]
@christofsteel Review?

**Comment by christofsteel** [comment]
Hey, awesome work, at first glance this looks really good. But before I start reviewing your code deeper, can you do three things:
  * rebase some of your commits together? Especially all the "Update herosaver.js" commits to logical units
  * remove all the console.log commands
  * make a separate pull request for the greasemonkey stuff

**Comment by christofsteel** [comment]
and one last thing: update the herosaver.min.js. To create it, I simply use uglify.js with the compress option.

**Comment by TeaWithLucas** [comment]
Hey, fairly new to public guys, how do I  do rebase commits and make separate commit for one file?
Thanks

**Comment by christopherjbaker** [comment]
@TeaWithLucas Rebasing them together is also sometime called squashing. This article has instructions for that https://github.com/wprig/wprig/wiki/How-to-squash-commits (note that you do not have to squash every commit in the list, only the ones you want to squash into the previous commit. Up to you where to draw that line.)

The easy way to separate out that file is to just create a new branch of master, put that file in it, and open a second PR. You'll need to commit the deletion then squash that new commit into whatever commit created the content (in order to remove traces of it).

**Pull request closed without merging**
